export const APPLICATION_ERRORS = 'APPLICATION_ERRORS';
export const APPLICATION_LOADING = 'APPLICATION_LOADING';
export const APPLICATION_LOADED = 'APPLICATION_LOADED';
export const COMMENTS_LOADED = 'COMMENTS_LOADED';
export const LOGGED_IN = 'LOGGED_IN';
export const LOGGED_OUT = 'LOGGED_OUT';
export const REGISTERED = 'REGISTERED';
export const SINGLE_AUTHOR_LOADED = 'SINGLE_AUTHOR_LOADED';
export const SINGLE_POST_LOADED = 'SINGLE_POST_LOADED';
export const TAGS_LOADED = 'TAGS_LOADED';
export const USER_DELETED = 'USER_DELETED';
export const USER_LOADED = 'USER_LOADED';

/* blog posts app constants (remove): */
export const POSTS_LOADED = 'POSTS_LOADED';
